#!/usr/bin/env bash
xrandr --output DP-0   --mode 1920x1080 --rotate normal --right-of DP-3 --primary
xrandr --output HDMI-0 --mode 1920x1080 --rotate normal --left-of  DP-0
#xrandr --output DP-3 --mode 1920x1080 --rotate normal --left-of  DP-0
